### ISSUE TITLE
About a cite of the project

### ISSUE THREAD

**Issue by purple7seven** [sneddy/pneumothorax-segmentation#2]
Thanks for your code. I want to use your code to test my experimental results in my paper. What do I need to cite in my reference?

**Comment by sneddy** [comment]
@misc{Aimoldin2019,
  author = {Aimoldin Anuar},
  title = {SIIM-ACR Pneumothorax Segmentation},
  year = {2019},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/sneddy/pneumothorax-segmentation}},
}

**Comment by sneddy** [comment]
> Thanks for your code. I want to use your code to test my experimental results in my paper. What do I need to cite in my reference?

**Comment by sneddy** [comment]
> Thanks for your code. I want to use your code to test my experimental results in my paper. What do I need to cite in my reference?

@misc{Aimoldin2019,
author = {Aimoldin Anuar},
title = {SIIM-ACR Pneumothorax Segmentation},
year = {2019},
publisher = {GitHub},
journal = {GitHub repository},
howpublished = {\url{https://github.com/sneddy/pneumothorax-segmentation}},
}
