### ISSUE TITLE
train_cfg issue

### ISSUE THREAD

**Issue by rkaiwang** [sneddy/pneumothorax-segmentation#5]
Hi @sneddy, thanks for sharing your great work!
I'm having an issue running your code after downloading it.
I'm getting this error, how do I resolve it?

Train.py: error: the following arguments are required: train_cfg

**Comment by sneddy** [comment]
you should specify the location of the training config.
for example:
```python
python Train.py experiments/albunet_valid/train_config_part0.yaml
```

**Comment by rkaiwang** [comment]
Thank you for your help! It worked, very much appreciated
